version: '3.8'
services:
  mysql:
    image: docker-registry.lcsb.uni.lu/library/mysql:5.7
    container_name: gpas-1.9.1-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sqls:/docker-entrypoint-initdb.d
      - mosaic_db_data:/var/lib/mysql
    networks:
      - mosaic
    labels:
      - "service-name:gpas"
      - "service-type:db-srv"
      - "environment:test"
  wildfly:
    image: docker-registry.lcsb.uni.lu/mosaicgreifswald/wildfly:18.0.1.Final-20191213
    container_name: gpas-1.9.1-wildfly
    links:
      - "mysql:mysqldb"
    networks:
      - mosaic
    environment:
      WILDFLY_PASS: wildfly_password
      JAVA_OPTS: ${JAVA_OPTS}
    depends_on:
      - mysql
    volumes:
      - ./jboss:/entrypoint-jboss-batch
      - ./deployments:/entrypoint-deployments
    labels:
      - "service-name:gpas"
      - "service-type:app-srv"
      - "environment:test"
    entrypoint: /bin/bash
    command: ["./wait-for-it.sh", "mysql:3306", "--", "./run.sh"]
  httpd:
    image: docker-registry.lcsb.uni.lu/library/httpd:2.4
    networks:
      - mosaic
    volumes:
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./httpd/mosaic.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ./httpd/ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
      - ./httpd/server.crt:/etc/ssl/certs/server.crt
      - ./httpd/server.key:/etc/ssl/private/server.key

networks:
  mosaic:
    driver: bridge


volumes:
  mosaic_db_data:

